name: stats
description: >-
  Calculate common statistical values for a set of numbers: max, min, mean,
  median, standard deviation, and standard error.
version: 0.2.0
homepage: https://github.com/kevmoo/stats
author: Kevin Moore <kevmoo@google.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^1.2.0

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  json_serializable: ^1.5.1
  pedantic: ^1.2.0
  test: ^1.3.0
